import Head from "next/head";
import { getLinksForTag } from "repositories/links";

export default function Home() {
  return (
    <div className="p-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hi</main>
    </div>
  );
}

export async function getServerSideProps() {
  const [js, home, web, tech] = await Promise.all([
    getLinksForTag("amorris-links-03", "js"),
    getLinksForTag("amorris-links-03", "home"),
    getLinksForTag("amorris-links-03", "web"),
    getLinksForTag("amorris-links-03", "tech"),
  ]);
  return {
    js,
    home,
    web,
    tech,
  };
}

// export async function getStaticProps({ params }) {
//   return {
//     props: {
//       links: await require("repositories/links").getLinksForTag(
//         "amorris-links-03",
//         params.tag
//       ),
//       tag: params.tag,
//     },
//     revalidate: 3600,
//   };
// }
